// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using AssignmentEf04.Models;

namespace AssignmentEf04.Context
{
    public partial class NORTHWNDContext
    {

        [DbFunction("CalculateOrderValue", "dbo")]
        public static int? CalculateOrderValue(int? OrderID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("GetCustomerOrderSummary", "dbo")]
        public IQueryable<GetCustomerOrderSummaryResult> GetCustomerOrderSummary(string CustomerID)
        {
            return FromExpression(() => GetCustomerOrderSummary(CustomerID));
        }

        [DbFunction("GetTopSellingProducts", "dbo")]
        public IQueryable<GetTopSellingProductsResult> GetTopSellingProducts(int? TopN)
        {
            return FromExpression(() => GetTopSellingProducts(TopN));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetCustomerOrderSummaryResult>().HasNoKey();
            modelBuilder.Entity<GetTopSellingProductsResult>().HasNoKey();
        }
    }
}
