// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AssignmentEf04.Context;
using AssignmentEf04.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace AssignmentEf04.Context.Configurations
{
    public partial class CustomersInGermanyConfiguration : IEntityTypeConfiguration<CustomersInGermany>
    {
        public void Configure(EntityTypeBuilder<CustomersInGermany> entity)
        {
            entity.ToView("CustomersInGermany");

            entity.Property(e => e.CustomerID).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CustomersInGermany> entity);
    }
}
