// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AssignmentEf04.Context;
using AssignmentEf04.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace AssignmentEf04.Context.Configurations
{
    public partial class LateShippedOrderConfiguration : IEntityTypeConfiguration<LateShippedOrder>
    {
        public void Configure(EntityTypeBuilder<LateShippedOrder> entity)
        {
            entity.ToView("LateShippedOrders");

            entity.Property(e => e.CustomerID).IsFixedLength();
            entity.Property(e => e.OrderID).ValueGeneratedOnAdd();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LateShippedOrder> entity);
    }
}
