// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AssignmentEf04.Context;
using AssignmentEf04.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace AssignmentEf04.Context.Configurations
{
    public partial class PriceUpdateLogConfiguration : IEntityTypeConfiguration<PriceUpdateLog>
    {
        public void Configure(EntityTypeBuilder<PriceUpdateLog> entity)
        {
            entity.HasKey(e => e.LogID).HasName("PK__PriceUpd__5E5499A87713454E");

            entity.Property(e => e.LogID).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PriceUpdateLog> entity);
    }
}
