// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssignmentEf04.Models
{
    public partial class GetCustomerOrderSummaryResult
    {
        [StringLength(50)]
        public string CustomerID { get; set; }
        public int? OrderYear { get; set; }
        public int? TotalOrders { get; set; }
    }
}
