// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssignmentEf04.Models
{
    public partial class GetEmployeesByDateRangeResult
    {
        public int EmployeeID { get; set; }
        [StringLength(10)]
        public string FirstName { get; set; }
        [StringLength(15)]
        public string Country { get; set; }
        public DateTime? ShippedDate { get; set; }
        public int OrderID { get; set; }
    }
}
