// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AssignmentEf04.Models;

[PrimaryKey("OrderID", "ProductID")]
[Table("Order Details")]
public partial class Order_Detail
{
    [Key]
    public int OrderID { get; set; }

    [Key]
    public int ProductID { get; set; }

    [Column(TypeName = "money")]
    public decimal UnitPrice { get; set; }

    public short Quantity { get; set; }

    public float Discount { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("Order_Details")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("Order_Details")]
    public virtual Product Product { get; set; }
}