// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AssignmentEf04.Models;

[Table("PriceUpdateLog")]
public partial class PriceUpdateLog
{
    [Key]
    public int LogID { get; set; }

    public int? ProductID { get; set; }

    [Column(TypeName = "money")]
    public decimal? OldPrice { get; set; }

    [Column(TypeName = "money")]
    public decimal? NewPrice { get; set; }

    public DateOnly? UpdateDate { get; set; }
}