// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AssignmentEf04.Models;

[Keyless]
public partial class ProductSalesSummary
{
    public int ProductID { get; set; }

    [Required]
    [StringLength(40)]
    public string ProductName { get; set; }

    [Required]
    [StringLength(15)]
    public string CategoryName { get; set; }

    public int? TotalUnitsSold { get; set; }

    public double? TotalRevenue { get; set; }
}