// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AssignmentEf04.Models
{
    public partial class Sp_GetCustomerOrderHistoryResult
    {
        [StringLength(40)]
        public string ProductName { get; set; }
        public int? TotalQuantityOrdered { get; set; }
    }
}
